sensors:
  right_bins_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]
    visualize_fov: true

  left_bins_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]
    visualize_fov: true

  conveyor_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-0.60, 3.06, 1.8]
      rpy: [pi, pi/2, 0]
    visualize_fov: true

  kts1_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-1.3, -5.8, 1.8]
      rpy: [pi, pi/2, pi/2]
    visualize_fov: true
  
  kts2_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-1.3, 5.8, 1.8]
      rpy: [pi, pi/2, -pi/2]
    visualize_fov: true
